repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    # TODO fix to match target directories
    files: (automation/|ci/|code-scanning/|deployments/|pages/).*(yaml|yml|json)$
