---
spring:
  # main:
  #   log-startup-info: true
  profiles:
    active: dev
  application:
    name: Chauncy
  logging:
    level:
      com.mediokr.chauncy: INFO

openai:
  api: token

gmail:
  api:
    client-id: token
    client-secret: token
    refresh-token: token

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: Chauncy (Dev)
  logging:
    level:
      com.mediokr.chauncy: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: Chauncy (Prod)
