---
name: Lint

on:
  push:

# Default permissions. Start limited, but change access as needed for jobs.
permissions:
  contents: read
  packages: read
  statuses: read

jobs:
  pre-commit:
    name: Pre-Commit Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install pre-commit
        run: ./scripts/setup.sh

      - name: Run pre-commit
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/clean-and-lint.sh
